In [1]:
import numpy as np
import scipy as spy

In [37]:
def reward(h,valve_position):
    area = 1
    cd = 1
    qout = np.sqrt(2*9.81*h) * valve_position * area * cd 
    if h >= 0.7 and h <=0.9:
        if qout >= 0 and qout <= 2:
            return 100
        else:
            return 0
    else:
        return 0

In [50]:
reward(0.8,0)


100

In [75]:
Q=np.zeros(shape=(10,10))
for i in range(0,10000):
    action = np.random.randint(0,10)
    state = np.random.randint(0,10)
    Q[state,action] = reward(state/10.0,action/10.0) +  0.6* np.amax(Q[state,])

In [77]:
print Q/np.amax(Q)

[[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 1.   1.   1.   1.   1.   1.   0.6  0.6  0.6  0.6]
 [ 1.   1.   1.   1.   1.   1.   0.6  0.6  0.6  0.6]
 [ 1.   1.   1.   1.   1.   0.6  0.6  0.6  0.6  0.6]]
